# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41d1d62bbdf00a0fc29f2e261c3a9e2e0612c1659456894128feebcf012b0e4eb224900f8b2d086df9a7dba9ab7d816987f944f017d8972525a5ee315b8b9ba

test:
  secret_key_base: d5a08db75cfc96d0d63f7d4b462fdb44093d9436dd32471ce84543f7430bb917bf2ef0098bcaccb8f33251979b7647f5d496d12e67f501f1d1d4491542a6ecc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
